// Downloads the US Census 2024 CBSA Gazetteer, parses it, and writes
// src/lib/msas.ts with all 384+ US Metropolitan Statistical Areas (Metro
// CBSAs only — Micropolitan and PR excluded). Public domain (17 USC §105).
//
// Run: node scripts/fetch-msas.mjs

import { writeFileSync } from "node:fs";
import path from "node:path";
import AdmZip from "adm-zip";

const URL =
  "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_cbsa_national.zip";

const STATE_SLUGS = {
  AL: "alabama", AK: "alaska", AZ: "arizona", AR: "arkansas",
  CA: "california", CO: "colorado", CT: "connecticut", DE: "delaware",
  DC: "districtofcolumbia", FL: "florida", GA: "georgia", HI: "hawaii",
  ID: "idaho", IL: "illinois", IN: "indiana", IA: "iowa",
  KS: "kansas", KY: "kentucky", LA: "louisiana", ME: "maine",
  MD: "maryland", MA: "massachusetts", MI: "michigan", MN: "minnesota",
  MS: "mississippi", MO: "missouri", MT: "montana", NE: "nebraska",
  NV: "nevada", NH: "newhampshire", NJ: "newjersey", NM: "newmexico",
  NY: "newyork", NC: "northcarolina", ND: "northdakota", OH: "ohio",
  OK: "oklahoma", OR: "oregon", PA: "pennsylvania", RI: "rhodeisland",
  SC: "southcarolina", SD: "southdakota", TN: "tennessee", TX: "texas",
  UT: "utah", VT: "vermont", VA: "virginia", WA: "washington",
  WV: "westvirginia", WI: "wisconsin", WY: "wyoming",
};

function citySlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

console.log("Fetching Census 2024 CBSA Gazetteer…");
const res = await fetch(URL);
if (!res.ok) {
  console.error(`Download failed: ${res.status} ${res.statusText}`);
  process.exit(1);
}
const buf = Buffer.from(await res.arrayBuffer());
const zip = new AdmZip(buf);
const entries = zip.getEntries();
const txtEntry = entries.find((e) => /\.txt$/i.test(e.entryName));
if (!txtEntry) {
  console.error("No .txt entry in ZIP");
  process.exit(1);
}
const txt = txtEntry.getData().toString("utf8");

const lines = txt.split(/\r?\n/);
const header = lines[0].split("\t").map((s) => s.trim());
const idx = (k) => header.indexOf(k);
const I_NAME = idx("NAME");
const I_TYPE = idx("CBSA_TYPE");
const I_GEOID = idx("GEOID");
const I_LAT = idx("INTPTLAT");
const I_LNG = idx("INTPTLONG");

const slugCounts = new Map();
const rows = [];

for (let i = 1; i < lines.length; i++) {
  const cols = lines[i].split("\t");
  if (cols.length < 5) continue;
  const cbsaType = (cols[I_TYPE] || "").trim();
  if (cbsaType !== "1") continue; // 1 = Metro, 2 = Micro
  const name = (cols[I_NAME] || "").trim();

  // Match "Houston-The Woodlands-Sugar Land, TX Metro Area"
  // Also handles multi-state e.g. "New York-Newark-Jersey City, NY-NJ-PA Metro Area"
  const m = name.match(/^(.+?),\s*([A-Z]{2}(?:-[A-Z]{2})*)\s+Metro Area$/);
  if (!m) continue;
  const titleBase = m[1];
  const stateCodes = m[2];
  const stateCode = stateCodes.split("-")[0];
  if (stateCode === "PR") continue;
  const stateSlug = STATE_SLUGS[stateCode];
  if (!stateSlug) continue;

  const principalCity = titleBase.split("-")[0].trim();
  const lat = parseFloat((cols[I_LAT] || "").trim());
  const lng = parseFloat((cols[I_LNG] || "").trim());
  if (!isFinite(lat) || !isFinite(lng)) continue;
  const cbsa = (cols[I_GEOID] || "").trim();

  const baseSlug = citySlug(principalCity);
  // Disambiguate by appending state code when slug collides across states
  const collisionKey = baseSlug;
  const seen = slugCounts.get(collisionKey) || 0;
  slugCounts.set(collisionKey, seen + 1);
  const slug =
    seen === 0 ? baseSlug : `${baseSlug}${stateCode.toLowerCase()}`;

  rows.push({
    cbsa,
    slug,
    iproyalCity: baseSlug,
    title: `${titleBase}, ${stateCodes}`,
    principalCity,
    stateCode,
    stateCodes,
    stateSlug,
    lat,
    lng,
  });
}

// Re-process: when the FIRST occurrence's slug collides later, also disambiguate
const finalSlugCounts = new Map();
rows.forEach((r) => {
  finalSlugCounts.set(r.slug, (finalSlugCounts.get(r.slug) || 0) + 1);
});
rows.forEach((r) => {
  if ((finalSlugCounts.get(r.slug) || 0) > 1) {
    r.slug = `${r.iproyalCity}${r.stateCode.toLowerCase()}`;
  }
});

rows.sort((a, b) => a.title.localeCompare(b.title));

const outPath = path.resolve(process.cwd(), "src/lib/msas.ts");
const ts =
  `// Auto-generated by scripts/fetch-msas.mjs from US Census 2024 CBSA Gazetteer.
// Public domain (17 USC §105). Do not edit by hand — re-run the script.

export type MSA = {
  cbsa: string;          // CBSA 5-digit code, e.g. "26420"
  slug: string;          // unique URL id
  iproyalCity: string;   // city slug for iproyal targeting (may collide across states)
  title: string;         // display title, e.g. "Houston-The Woodlands-Sugar Land, TX"
  principalCity: string; // principal city, e.g. "Houston"
  stateCode: string;     // primary state, e.g. "TX"
  stateCodes: string;    // multi-state if applicable, e.g. "NY-NJ-PA"
  stateSlug: string;     // iproyal state slug, e.g. "texas"
  lat: number;           // CBSA centroid latitude
  lng: number;           // CBSA centroid longitude
};

export const MSAS: MSA[] = ${JSON.stringify(rows, null, 2)};

const BY_SLUG = new Map<string, MSA>(MSAS.map((x) => [x.slug, x]));
const BY_CBSA = new Map<string, MSA>(MSAS.map((x) => [x.cbsa, x]));

export function findMsa(slug: string | null | undefined): MSA | null {
  if (!slug) return null;
  return BY_SLUG.get(slug) ?? null;
}

export function findMsaByCbsa(cbsa: string): MSA | null {
  return BY_CBSA.get(cbsa) ?? null;
}

// Haversine distance in miles between two lat/lng points.
export function distanceMiles(
  aLat: number,
  aLng: number,
  bLat: number,
  bLng: number,
): number {
  const R = 3958.8; // Earth radius in miles
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(bLat - aLat);
  const dLng = toRad(bLng - aLng);
  const sinDLat = Math.sin(dLat / 2);
  const sinDLng = Math.sin(dLng / 2);
  const a =
    sinDLat * sinDLat +
    Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * sinDLng * sinDLng;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(a)));
}

// Returns the MSA closest to (lat,lng), with the distance in miles.
export function nearestMsa(
  lat: number,
  lng: number,
): { msa: MSA; distanceMiles: number } | null {
  if (!isFinite(lat) || !isFinite(lng)) return null;
  let best: { msa: MSA; distanceMiles: number } | null = null;
  for (const msa of MSAS) {
    const d = distanceMiles(lat, lng, msa.lat, msa.lng);
    if (!best || d < best.distanceMiles) best = { msa, distanceMiles: d };
  }
  return best;
}
`;

writeFileSync(outPath, ts);
console.log(`Wrote ${rows.length} MSAs to ${outPath}`);
